### ISSUE TITLE
T3 Entries Removed From Trait Dictionary

### ISSUE THREAD

**Issue by dwaring87** [Planteome/ibp-oat-traits#6]
It looks like the latest commit b68fa0f741 made by @marieALaporte removed the T3 variables from the trait dictionary - the change removed 329 lines from the file and added back only 229.

**Comment by marieALaporte** [comment]
Thanks @dwaring87. I must have made a mistake somewhere. Let me check and add back what I removed.

**Comment by marieALaporte** [comment]
Fixed
